/** Declaration file generated by dts-gen */

export class EventManager {
    constructor();

    addEvent(event: string, fn: any, context: any, once: boolean): void;

    clear(event: string): void;

    contains(event: string): any;

    emit(event: string, ...args: any[]): void;

    get(event: string): any;

    on(event: string, fn: any, context: any): void;

    once(event: string, fn: any, context: any): void;

}

