/** Declaration file generated by dts-gen */

export class EventManager {
    constructor();

    addEvent(event: any, fn: any, context: any, once: any): void;

    clear(event: any): void;

    contains(event: any): any;

    emit(event: any, ...args: any[]): void;

    get(event: any): any;

    on(event: any, fn: any, context: any): void;

    once(event: any, fn: any, context: any): void;

}

